config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles, only: [:index, :show, :create, :update, :destroy]
    resources :categories, only: [:index, :show, :create, :update, :destroy] do
      member do
        patch :update_position
      end
    end
    resources :rails_versions, only: [:index, :show, :create, :update, :destroy]
  end

  get 'admin' => 'admin/articles#index'
  
  resources :articles, only: [:index, :show] do 
    collection do
      get :get_started
      get :what_next
    end
  end
  resources :categories
  resources :rails_versions
  devise_for :users
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  belongs_to :rails_version

  validates_presence_of :key, :github_link, :author_name, :title
  validates_uniqueness_of :key

  scope :by_category,             -> (category) { where( category_id: category )}
  scope :by_rails_version,             -> (rails_version) { where( rails_version_id: rails_version )}

  before_validation :set_attributes, :on => :create

  private

  def set_attributes
    self.piblished_at = Time.now
  end

  def self.search_by_text(query)
    where(<<-SQL, "%#{query.downcase}%" )
      articles.title ilike ?
    SQL
  end

  def self.get_articles_list
    list = []
    Category.where(parent_category_id: nil).order("position").each do |c|
      list << c.get_articles(c.articles.pluck(:id))
    end
    list
  end

  def set_attributes
    self.key = Article.all.count == 0 ? "article-key-1" : "article-key-#{Article.last.id + 1}"
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  require 'octokit'
  layout 'admin'

  before_action :set_article, only: %i[ show edit update destroy ]

  def index
    @articles = Article.all
    @articles = @articles.paginate(:page => params[:page], :per_page => 10)

    @article = Article.new
    @rails_versions = RailsVersion.all
    @rails_versions = @rails_versions.active if @rails_versions.count != 0
    @categories = Category.all
    @categories = @categories.active if @categories.count != 0
  end

  def show
    client = Octokit::Client.new(:access_token => "#{Figaro.env.GITHUB_ACCESS_TOKEN}")
    @response = client.contents("#{Figaro.env.GITHUB_REPO}", path: @article.github_link, query: {},  :accept => 'application/vnd.github.html')
    @suggested_articles = Article.by_category(@article.category_id).where.not(id: params[:id]).limit(10)
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to admin_articles_url, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to admin_articles_url, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:category_id, :rails_version_id, :title, :key, :github_link, :author_name, :piblished_at)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  require 'octokit'
  skip_before_action :authenticate_user!
  before_action :set_article, only: %i[ show ]

  def index
    @articles = Article.all.order("created_at DESC")
    @articles = @articles.by_category(params[:category_id]) if params[:category_id].present?
    @articles = @articles.by_rails_version(params[:rails_version_id]) if params[:rails_version_id].present?
    @articles = @articles.search_by_text(params[:search]) if params[:search].present?

    @categories = Category.active
    @rails_versions = RailsVersion.active
  end

  def show
    client = Octokit::Client.new(:access_token => "#{Figaro.env.GITHUB_ACCESS_TOKEN}")
    @response = client.contents("#{Figaro.env.GITHUB_REPO}", path: @article.github_link, query: {},  :accept => 'application/vnd.github.html')
    @suggested_articles = Article.where(category_id: @article.category.get_parent_categories(@article.category.try(:id), [])).where.not(id: params[:id]).limit(10)

    _article_index = nil
    _articles_list = Article.get_articles_list
    _articles_list.flatten.each_with_index{|e,i| _article_index = i if e == @article.id}
    if _article_index == 0
      @previous_article = nil
      @next_article = Article.find_by_id(_articles_list.flatten[1])
    elsif _article_index == _articles_list.flatten.count - 1
      @previous_article = Article.find_by_id(_articles_list.flatten[_article_index - 1])
      @next_article = nil
    else
      @previous_article = Article.find_by_id(_articles_list.flatten[_article_index - 1])
      @next_article = Article.find_by_id(_articles_list.flatten[_article_index + 1])
    end
  end

  def get_started
    _articles_list = Article.get_articles_list
    @next_article = _articles_list.flatten.count > 0 ? Article.find_by_id(_articles_list.flatten[0]) : nil
    @categories = Category.order(:position).joins(:articles).uniq
  end

  def what_next
    _articles_list = Article.get_articles_list
    @previous_article = _articles_list.flatten.count > 0 ? Article.find_by_id(_articles_list.flatten[-1]) : nil
  end

  private 

  def set_article
    @article = Article.find_by_id(params[:id])
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_side_nav.html.haml
%aside#logo-sidebar.fixed.top-0.left-0.w-64.h-screen.bg-white.border-r.border-gray-200.dark:bg-gray-800.dark:border-gray-700
	- if @article.present?
		= hidden_field :parent_category_ids, @article.category.get_parent_categories(@article.category.try(:id), []), {value: @article.category.get_parent_categories(@article.category.try(:id), []), id: 'sidebar-active-article'}
	.px-1.pb-4.bg-white.dark:bg-gray-800
		%a.flex.items-center.grow.py-8{:href => "https://railsmojo.org/"}
			= image_tag 'railsmojo-logo.png', class: "h-6 mr-3 sm:h-9", id: "light-logo"
			= image_tag 'railsmojo-logo-dark.png', class: "h-6 mr-3 sm:h-9", id: "dark-logo"

	= link_to "Get Started", get_started_articles_path, class: "flex.items-center w-full p-1 text-sm font-normal text-gray-900 transition duration-75 rounded-lg group dark:text-white"
	- Category.where(parent_category_id: nil).order("position").each do |category|
		%button.flex.items-center.w-full.p-1.text-sm.font-normal.text-gray-900.transition.duration-75.rounded-lg.group.dark:text-white{"aria-controls" => "dropdown-category-#{category.try(:id)}", "data-collapse-toggle" => "dropdown-category-#{category.try(:id)}", type: "button"}
			%svg.w-5.h-5{fill: "currentColor", "sidebar-toggle-item" => "", viewbox: "0 0 20 20", xmlns: "http://www.w3.org/2000/svg"}
				%path{"clip-rule" => "evenodd", d: "M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z", "fill-rule" => "evenodd"}
			%span.flex-1.ml-3.text-left.whitespace-nowrap{"sidebar-toggle-item" => ""}= category.try(:name)
		%ul.hidden.ml-4.border-l.border-gray-200.dark:border-gray-700{id: "dropdown-category-#{category.try(:id)}"}
			= category.get_sub_categories(category.categories, category.articles).html_safe
	= link_to "What Next", what_next_articles_path, class: "flex.items-center w-full p-1 text-sm font-normal text-gray-900 transition duration-75 rounded-lg group dark:text-white"

app/views/articles/get_started.html.haml
.mt-0
  = render 'articles/side_nav'
  .sm:ml-64.pt-20.p-4
    %section

    .py-8.px-4.mx-auto.max-w-screen-xl.text-center.mb-12.lg:py-16.lg:px-12
      .flex.items-center.justify-center
        %div
          %h1.max-w-4xl.mb-4.text-center.text-4xl.font-extrabold.tracking-tight.leading-tight.text-gray-900.md:text-5xl.lg:text-7xl.lg:leading-tight.dark:text-white 
            Get Started with
          %h1.bg-red-600.rounded.max-w-4xl.mb-4.text-center.text-4xl.font-extrabold.tracking-tight.leading-tight.text-white.md:text-5xl.lg:text-7xl.lg:leading-tight.dark:text-white 
            Ruby on Rails
      %p.mb-8.text-base.font-normal.text-gray-500.lg:text-lg.sm:px-16.xl:px-48.dark:text-gray-400 
        Explore our amazing collection of 
        %i how to guides, 
        which will help you to solve any problem statement.
        Follow the practical step-by-step guides and bring your ideas into reality.
    

    .grid.grid-cols-12.gap-4
      - @categories.each do |category|
        .col-span-12.grid.grid-cols-12.gap-4.card
          .col-span-6
            = link_to articles_path(category_id: category.id), data: {turbo: true, "turbo_frame": "articles"} do
              .px-4.py-2
                .flex.flex-col.items-start
                  .flex.items-start.justify-start
                    %svg.h-9.w-9.mr-4.fill-gray-600.dark:fill-gray-400{:viewbox => "0 01 50 50", :xmlns => "http://www.w3.org/2000/svg"}
                      %path{"clip-rule" => "evenodd", :d => "M6.6 25.5V37 11v14.5ZM27.55 43q1 0 1.725-.75.725-.75.725-1.8 0-1-.725-1.725Q28.55 38 27.5 38q-1 0-1.75.725T25 40.5q0 1 .75 1.75t1.8.75Zm13-21q1 0 1.725-.75.725-.75.725-1.8 0-1-.725-1.725Q41.55 17 40.5 17q-1 0-1.75.725T38 19.5q0 1 .75 1.75t1.8.75ZM12 21h10v-3H12Zm0 9h10v-3H12ZM6.6 40q-1.2 0-2.1-.9-.9-.9-.9-2.1V11q0-1.2.9-2.1.9-.9 2.1-.9h34.8q1.2 0 2.1.9.9.9.9 2.1H6.6v26H19v3Zm20.9 6q-2.3 0-3.9-1.6T22 40.5q0-1.9 1.125-3.35Q24.25 35.7 26 35.2v-6.7h13v-3.7q-1.75-.5-2.875-1.95T35 19.5q0-2.3 1.6-3.9t3.9-1.6q2.3 0 3.9 1.6t1.6 3.9q0 1.9-1.125 3.35Q43.75 24.3 42 24.8v6.7H29v3.7q1.75.5 2.875 1.95T33 40.5q0 2.3-1.6 3.9T27.5 46Z"}
                    %div
                      %h3.text-2xl.font-semibold.text-gray-600.dark:text-white 
                        %span.text-emerald-500	
                          How-to 
                        Guides
                        %span.mb-2.text-base.font-medium.text-gray-500.dark:text-gray-400 
                          for
                          %span.font-bold= category.try(:name)                 

                      %p.py-3.text-gray-500.text-sm.dark:text-gray-400{class: "w-4/5"}= category.try(:description)
                      = link_to articles_path(category_id: category.id) do
                        .mt-2.text-xs.text-gray-500.uppercase.flex.items-center.hover:text-rose-500
                          = "#{category.articles.count} articles"
                          %svg.ml-2.-mr-1.w-4.h-4{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
                            %path{"clip-rule" => "evenodd", :d => "M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z", "fill-rule" => "evenodd"}
          
          .col-span-6.flex.items-center
            %div
              - category.articles.first(3).each do |article|
                .w-full.flex.items-start.justify-start.gap-4.text-gray-700.dark:text-gray-400.rounded-lg.dark:text-white
                  %svg.text-gray-700.dark:text-gray-400.mt-1.h-4.w-4{fill: "currentColor", height: "1em", viewbox: "0 0 24 24", width: "1em", xmlns: "http://www.w3.org/2000/svg"}
                    %path{d: "M0 0h24v24H0z", fill: "none"}
                    %path{d: "M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-5 14H7v-2h7v2zm3-4H7v-2h10v2zm0-4H7V7h10v2z"}
                  = link_to article.try(:title), article_path(article), class: "font-medium text-gray-700 dark:text-gray-400 hover:underline"
              - if category.articles.count > 3
                = link_to articles_path(category_id: category.id) , class: "mt-2 text-sm text-gray-500 flex items-center hover:text-rose-500" do
                  %svg.h-4.w-4{fill: "currentColor", height: "1em", stroke: "currentColor", "stroke-width" => "0", viewbox: "0 0 24 24", width: "1em", xmlns: "http://www.w3.org/2000/svg"}
                    %path{d: "M0 0h24v24H0V0z", fill: "none"}
                    %path{d: "M19 15l-6 6-1.42-1.42L15.17 16H4V4h2v10h9.17l-3.59-3.58L13 9l6 6z"}
                  See All

  .flex.justify-end.items-center.my-6.px-2
    = link_to @next_article.present? ? article_path(@next_article) : what_next_articles_path, class: "py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" do
      = @next_article.present? ? @next_article.try(:title) : "What Next"
      %span.ml-2{"aria-hidden" => "true"} →

app/views/articles/index.html.haml
.mt-0
  = render 'articles/side_nav'
  .sm:ml-64.pt-20.p-4
    %h2.mb-4.text-4xl.font-extrabold.leading-none.tracking-tight.text-gray-900.md:text-4xl.lg:text-4xl.dark:text-white Articles

    = form_with( url: Rails.application.routes.url_helpers.articles_path, method: :get, data: { turbo: true, "turbo-frame": "articles" }) do |f|
      .flex.justify-between.align-center.p-2
        .flex.items-center.gap-4
          = f.select :category_id, options_for_select(@categories.collect{|c| [c.try(:name), c.try(:id)]}, params[:category_id]), {include_blank: "Select Category"} , {onchange: "javascript:this.form.commit.click();", class: "inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"} 
          = f.select :rails_version_id, options_for_select(@rails_versions.collect{|v| [v.try(:name), v.try(:id)]}, params[:rails_version_id]), {include_blank: "Select Rails Version"} , {onchange: "javascript:this.form.commit.click();", class: "inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"} 
          = f.submit 'save', class: "hidden"
      
        .relative
          .absolute.inset-y-0.left-0.flex.items-center.pl-3.pointer-events-none
            %svg.w-5.h-5.text-gray-500.dark:text-gray-400{"aria-hidden" => "true", :fill => "none", :stroke => "currentColor", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
              %path{:d => "M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
          = f.text_field :search, placeholder: "Search by article", class: "block p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"      

    = turbo_frame_tag "articles" do
      .grid.grid-cols-12.gap-4.my-4
        - @articles.each do |article|
          .col-span-4 
            = link_to article_path(article), class: "block p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700" do
              %h5.mb-2.text-2xl.font-bold.tracking-tight.text-gray-900.dark:text-white= article.try(:title)
              %p.font-normal.text-gray-700.dark:text-gray-400= article.category.try(:name)
              %p.font-normal.text-gray-700.dark:text-gray-400= "Rails #{article.rails_version.try(:name)}"

app/views/articles/show.html.haml
.mt-0
  = render 'articles/side_nav'
  .sm:ml-64.pt-20.p-4
    .px-2
      -# %p.font-normal.text-gray-700.dark:text-gray-400= @article.category.try(:name).try(:humanize)
      %p.font-normal.text-gray-700.dark:text-gray-400= "Rails #{@article.rails_version.try(:name).try(:humanize)}"
      %h2.mb-4.text-4xl.font-extrabold.leading-none.tracking-tight.text-gray-900.md:text-4xl.lg:text-4xl.dark:text-white= @article.title

    .grid.grid-cols-12.gap-4.mt-4
      .col-span-8.p-2
        .md_content.w-full.block.p-4.bg-white.border.border-gray-200.rounded-lg.shadow.dark:bg-gray-800.dark:border-gray-700
          = @response.html_safe
      .col-span-4.p-2
        %h4.mb-4.text-2xl.font-extrabold.leading-none.tracking-tight.text-gray-900.md:text-2xl.lg:text-2xl.dark:text-white Other Articles
        .grid.grid-cols-12.gap-4.mt-4
          - @suggested_articles.each do |article|
            .col-span-12
              = link_to article_path(article), class: "block max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700" do
                %h5.mb-2.text-xl.font-bold.tracking-tight.text-gray-900.dark:text-white= article.try(:title)
                %p.font-normal.text-gray-700.dark:text-gray-400= "Rails #{article.rails_version.try(:name)}"

    .flex.justify-between.items-center.my-6.px-2
      = link_to @previous_article.present? ? article_path(@previous_article) : get_started_articles_path, class: "py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" do
        %span.mr-2{"aria-hidden" => "true"} ←
        = @previous_article.present? ? @previous_article.try(:title) : "Get Started"
        
      = link_to @next_article.present? ? article_path(@next_article) : what_next_articles_path, class: "py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" do
        = @next_article.present? ? @next_article.try(:title) : "What Next"
        %span.ml-2{"aria-hidden" => "true"} →

app/views/articles/what_next.html.haml
.mt-0
  = render 'articles/side_nav'
  .sm:ml-64.pt-20.p-4
    .px-2
      %p.font-normal.text-gray-700.dark:text-gray-400 What Next
      %h2.mb-4.text-4xl.font-extrabold.leading-none.tracking-tight.text-gray-900.md:text-4xl.lg:text-4xl.dark:text-white What Next
    .flex.justify-start.items-center.my-6.px-2
      = link_to @previous_article.present? ? article_path(@previous_article) : get_started_articles_path, class: "py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" do
        %span.mr-2{"aria-hidden" => "true"} ←
        = @previous_article.present? ? @previous_article.try(:title) : "Get Started"