config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles, only: [:index, :show, :create, :update, :destroy]
    resources :categories, only: [:index, :show, :create, :update, :destroy] do
      member do
        patch :update_position
      end
    end
    resources :rails_versions, only: [:index, :show, :create, :update, :destroy]
  end

  get 'admin' => 'admin/articles#index'
  
  resources :articles, only: [:index, :show] do 
    collection do
      get :get_started
      get :what_next
    end
  end
  resources :categories
  resources :rails_versions
  devise_for :users
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :rails_version
  belongs_to :parent_category, optional: true, class_name: 'Category', inverse_of: :categories
  has_many :articles
  has_many :categories, foreign_key: :parent_category_id, dependent: :destroy, inverse_of: :parent_category

  validates_presence_of :name, :slug, :position, :description
  validates_uniqueness_of :name, :slug

  scope :active, ->               { where( is_active: true )}

  before_validation :set_attributes, :on => :create

  def get_sub_categories(categories, articles)
    str = ""
    articles.each { |a|
      str += "<li class='py-1 px-2 text-sm font-semibold text-gray-900 transition duration-75 rounded-lg group dark:text-white'><a href='/articles/#{a.try(:id)}'>#{a.try(:title)}</a></li>"
    } 

    categories.each { |c|
      str +=  "<li><button type=button class='flex items-center w-full p-1 text-sm font-normal text-gray-900 transition duration-75 rounded-lg group dark:text-white' aria-controls='dropdown-category-#{c.try(:id)}' data-collapse-toggle='dropdown-category-#{c.try(:id)}'>
      <svg sidebar-toggle-item class='w-5 h-5' fill=currentColor viewBox='0 0 20 20' xmlns='http://www.w3.org/2000/svg'><path fill-rule=evenodd d='M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z' clip-rule=evenodd></path></svg><span class='flex-1 ml-3 text-left whitespace-nowrap' sidebar-toggle-item>#{c.try(:name)}</span></button>"
      str += "<ul class='hidden ml-4 border-l border-gray-200 dark:border-gray-700' id='dropdown-category-#{c.try(:id)}' >"
      str += c.get_sub_categories(c.categories.order("position"), c.articles )
      str += "</ul>"
      str += "</li>"
    }
    return str
  end

  def get_articles articles
    arr = articles
    self.articles.each {|a| arr << a.id}
    self.categories.order("position").each { |c| c.get_articles(arr) }
    arr.flatten.uniq
  end

  def get_parent_categories(category_id, arrs)
    _arr = arrs
    _cat = Category.find_by_id(category_id)
    _arr << category_id if  _cat.present?

    _cat.get_parent_categories(_cat.parent_category_id, _arr) if  _cat.try(:parent_category_id).present?
    _arr
  end

  def change_category_position position 
    notice = ""
    if self.position.to_i > position.to_i # move top
      Category.where("position BETWEEN ? AND ?", position.to_i, self.position.to_i - 1).each { |cat| cat.update(position: cat.position + 1) }
    elsif self.position.to_i < position.to_i # move bottom
      Category.where("position BETWEEN ? AND ?", self.position.to_i + 1, position.to_i).each { |cat| cat.update(position: cat.position - 1) }
    end
    if self.update(position: position)
      notice = "success"
    end
  end

  private

  def set_attributes
    self.slug = Category.all.count == 0 ? "category-1" : "category-#{Category.last.id + 1}"
    self.position = Category.all.count == 0 ? 1 : Category.all.pluck(:position).max.to_i + 1
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout 'admin'
  before_action :set_category, only: %i[ show edit update destroy update_position ]

  def index
    @categories = Category.all.order("position")
    @categories = @categories.paginate(:page => params[:page], :per_page => 10)

    @category = Category.new
    @rails_versions = RailsVersion.all
    @rails_versions = @rails_versions.active if @rails_versions.count != 0
  end

  def show
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_url, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_url, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def update_position
    if @category.present? and @category.try(:position).present? and params[:position].present?
      result = @category.change_category_position params[:position]
      respond_to do |format|
        if result == 'success'
          format.html { redirect_to admin_categories_path, notice: "Categories were successfully sorted." }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:rails_version_id, :name, :slug, :position, :is_active, :description, :parent_category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:rails_version_id, :name, :slug, :position, :is_active)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.haml
= form_with(model: category, url: (category.persisted? ? Rails.application.routes.url_helpers.admin_category_path(category) : Rails.application.routes.url_helpers.admin_categories_path), class: "contents", data: { turbo_frame: "_top"}) do |form|
  .flex.items-start.justify-between.p-4.border-b.rounded-t.dark:border-gray-600
    %h3.text-xl.font-semibold.text-gray-900.dark:text-white= category.persisted? ? "Update Category" : "Create Category"
    %button.text-gray-400.bg-transparent.hover:bg-gray-200.hover:text-gray-900.rounded-lg.text-sm.ml-auto.inline-flex.items-center.dark:hover:bg-gray-600.dark:hover:text-white{class: "p-1.5", "data-modal-hide" => category.persisted? ? "category_#{category.id}" : category.parent_category_id.present? ? "new_sub_category_#{category.parent_category_id}" : "category_new", type: "button"}
      %svg.w-5.h-5{"aria-hidden" => "true", fill: "currentColor", viewbox: "0 0 20 20", xmlns: "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", d: "M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z", "fill-rule" => "evenodd"}
      %span.sr-only Close modal
  .grid.grid-cols-12.gap-4.px-4.py-6
    .col-span-6
      = form.label :name, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"
      = form.text_field :name, required: true, class: "go-text-field"
    .col-span-6
      = form.label :rails_version, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"
      = form.select :rails_version_id, options_for_select(@rails_versions.collect{|v| [v.try(:name), v.try(:id)]}, category.try(:rails_version_id)), {} , {class: "go-text-field"} 
    .col-span-6
      = form.label :parent_category_id, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"
      = form.select :parent_category_id, options_for_select(Category.all.collect{|v| [v.try(:name), v.try(:id)]}, category.try(:parent_category_id)), {include_blank: 'Select Parent Category'} , {class: "go-text-field"} 
    .col-span-6
      = form.label :description, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"
      = form.text_area :description, required: true, class: "go-text-field"

    .col-span-12.flex.items-center.gap-4
      = form.check_box :is_active, {class: "w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800", :type => "button"}
      = form.label :is_active, "Active?", class: "block text-sm font-medium text-gray-900 dark:text-white"

  .p-4.flex.justify-end.items-center.gap-4.border-t.dark:border-gray-600
    = form.submit "Submit", class: "block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm py-2 px-5 cursor-pointer text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
    %button.text-gray-500.bg-white.hover:bg-gray-100.focus:ring-4.focus:outline-none.focus:ring-blue-300.rounded-lg.border.border-gray-200.text-sm.font-medium.px-5.hover:text-gray-900.focus:z-10.dark:bg-gray-700.dark:text-gray-300.dark:border-gray-500.dark:hover:text-white.dark:hover:bg-gray-600.dark:focus:ring-gray-600{class: "py-2.5", "data-modal-hide" => category.persisted? ? "category_#{category.id}" : category.parent_category_id.present? ? "new_sub_category_#{category.parent_category_id}" : "category_new", type: "button"} Decline

app/views/admin/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/admin/categories/index.html.haml
.flex.items-center.justify-between.mb-2
	%h3.mb-4.text-2xl.font-extrabold.leading-none.tracking-tight.text-gray-900.md:text-2xl.lg:text-2xl.dark:text-white Categories
	%button.block.text-white.bg-blue-700.hover:bg-blue-800.focus:ring-4.focus:outline-none.focus:ring-blue-300.font-medium.rounded-lg.text-sm.px-5.text-center.dark:bg-blue-600.dark:hover:bg-blue-700.dark:focus:ring-blue-800{class: "py-2.5", "data-modal-target" => "category_new", "data-modal-toggle" => "category_new", type: "button"}
		New Category
#category_new.fixed.top-0.left-0.right-0.z-50.hidden.w-full.p-4.overflow-x-hidden.overflow-y-auto.md:inset-0.h-modal.md:h-full{"aria-hidden" => "true", tabindex: "-1"}
	.relative.w-full.h-full.max-w-2xl.md:h-auto
		.relative.bg-white.rounded-lg.shadow.dark:bg-gray-700
			= render "admin/categories/form", category: @category

.relative.overflow-x-auto.shadow-md.sm:rounded-lg
	= turbo_frame_tag "admin_categories" do
		%table.w-full.text-sm.text-left.text-gray-500.dark:text-gray-400
			%thead.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
				%tr
					%th.px-6.py-3{scope: "col"}
						Name
					%th.px-6.py-3{scope: "col"}
						Parent Category
					%th.px-6.py-3{scope: "col"}
						Rails Version
					%th.px-6.py-3{scope: "col"}
						Articles
					%th.px-6.py-3{scope: "col"}
						Sub categories
					%th.px-6.py-3{scope: "col"}
						
			%tbody{"data-controller" => "sortable"}
				- @categories.each do |category|					
					%tr.bg-white.border-b.dark:bg-gray-800.dark:border-gray-700.hover:bg-gray-50.dark:hover:bg-gray-600{"data-sortable-update-url" => update_position_admin_category_path(category)}
						%td.px-6.py-4.font-medium.text-gray-900.whitespace-nowrap.dark:text-white.flex.gap-4.items-center{scope: "row"}
							%span.flex.w-2.h-2.rounded-full{class: category.try(:is_active) ? 'bg-green-600' : 'bg-orange-600' }
							= category.try(:name)
						%td.px-6.py-4
							= category.try(:parent_category).try(:name)
						%td.px-6.py-4
							= category.try(:rails_version).try(:name)
						%td.px-6.py-4
							= category.articles.count
						%td.px-6.py-4
							= category.categories.count
						%td.px-6.py-4
							.flex.items-center.gap-4
								.font-medium.text-blue-600.dark:text-blue-500.cursor-pointer{"data-modal-target" => "category_#{category.try(:id)}", "data-modal-toggle" => "category_#{category.try(:id)}", type: "button"} Edit
								.font-medium.text-red-600.dark:text-red-500.cursor-pointer{"data-modal-target" => "delete_category_#{category.try(:id)}", "data-modal-toggle" => "delete_category_#{category.try(:id)}", type: "button"} Destroy
								.font-medium.text-blue-600.dark:text-blue-500.cursor-pointer{"data-modal-target" => "new_sub_category_#{category.try(:id)}", "data-modal-toggle" => "new_sub_category_#{category.try(:id)}", type: "button"} New
							
							.fixed.top-0.left-0.right-0.z-50.hidden.w-full.p-4.overflow-x-hidden.overflow-y-auto.md:inset-0.h-modal.md:h-full{id: "category_#{category.try(:id)}", "aria-hidden" => "true", tabindex: "-1"}
								.relative.w-full.h-full.max-w-2xl.md:h-auto
									.relative.bg-white.rounded-lg.shadow.dark:bg-gray-700
										= render "admin/categories/form", category: category
							.fixed.top-0.left-0.right-0.z-50.hidden.p-4.overflow-x-hidden.overflow-y-auto.md:inset-0.h-modal.md:h-full{id: "delete_category_#{category.try(:id)}", "aria-hidden" => "true", tabindex: "-1"}
								.relative.w-full.h-full.max-w-md.md:h-auto
									.relative.bg-white.rounded-lg.shadow.dark:bg-gray-700
										= render "admin/shared/destroy_modal", model: category, url: Rails.application.routes.url_helpers.admin_category_path(category), id: "delete_category_#{category.try(:id)}", confirm_text: "Are you sure you want to delete this category?"
							.fixed.top-0.left-0.right-0.z-50.hidden.w-full.p-4.overflow-x-hidden.overflow-y-auto.md:inset-0.h-modal.md:h-full{id: "new_sub_category_#{category.try(:id)}", "aria-hidden" => "true", tabindex: "-1"}
								.relative.w-full.h-full.max-w-2xl.md:h-auto
									.relative.bg-white.rounded-lg.shadow.dark:bg-gray-700
										- new_category = Category.new(parent_category_id: category.try(:id))
										= render "admin/categories/form", category: new_category
		
		
		.flex.justify-center
			= will_paginate @categories, :class => "will_pag py-2"

app/views/admin/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/admin/categories/show.html.haml
%h1 Admin::Categories#show
%p Find me in app/views/admin/categories/show.html.haml