config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles, only: [:index, :show, :create, :update, :destroy]
    resources :categories, only: [:index, :show, :create, :update, :destroy] do
      member do
        patch :update_position
      end
    end
    resources :rails_versions, only: [:index, :show, :create, :update, :destroy]
  end

  get 'admin' => 'admin/articles#index'
  
  resources :articles, only: [:index, :show] do 
    collection do
      get :get_started
      get :what_next
    end
  end
  resources :categories
  resources :rails_versions
  devise_for :users
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/rails_version.rb
class RailsVersion < ApplicationRecord
    has_many :articles
    has_many :categories

    validates_presence_of :name, :slug
    validates_uniqueness_of :name, :slug

    scope :active, ->               { where( is_active: true )}

    before_validation :set_attributes, :on => :create

    private

    def set_attributes
        self.slug = RailsVersion.all.count == 0 ? "version-1" : "version-#{RailsVersion.last.id + 1}"
    end

end

app/controllers/admin/rails_versions_controller.rb
class Admin::RailsVersionsController < ApplicationController
  layout 'admin'
  before_action :set_rails_version, only: %i[ show edit update destroy ]

  def index
    @rails_versions = RailsVersion.all
    @rails_versions = @rails_versions.paginate(:page => params[:page], :per_page => 10)

    @rails_version = RailsVersion.new
  end

  def show
  end

  def create
    @rails_version = RailsVersion.new(rails_version_params)
    respond_to do |format|
      if @rails_version.save
        format.html { redirect_to admin_rails_versions_url, notice: "Rails version was successfully created." }
        format.json { render :show, status: :created, location: @rails_version }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rails_version.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @rails_version.update(rails_version_params)
        format.html { redirect_to admin_rails_versions_url, notice: "Rails version was successfully updated." }
        format.json { render :show, status: :ok, location: @rails_version }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rails_version.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rails_version.destroy

    respond_to do |format|
      format.html { redirect_to admin_rails_versions_url, notice: "Rails version was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_rails_version
      @rails_version = RailsVersion.find(params[:id])
    end

    def rails_version_params
      params.require(:rails_version).permit(:name, :slug, :is_default, :is_active)
    end
end

app/controllers/rails_versions_controller.rb
class RailsVersionsController < ApplicationController
  before_action :set_rails_version, only: %i[ show edit update destroy ]

  # GET /rails_versions or /rails_versions.json
  def index
    @rails_versions = RailsVersion.all
  end

  # GET /rails_versions/1 or /rails_versions/1.json
  def show
  end

  # GET /rails_versions/new
  def new
    @rails_version = RailsVersion.new
  end

  # GET /rails_versions/1/edit
  def edit
  end

  # POST /rails_versions or /rails_versions.json
  def create
    @rails_version = RailsVersion.new(rails_version_params)

    respond_to do |format|
      if @rails_version.save
        format.html { redirect_to rails_version_url(@rails_version), notice: "Rails version was successfully created." }
        format.json { render :show, status: :created, location: @rails_version }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rails_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rails_versions/1 or /rails_versions/1.json
  def update
    respond_to do |format|
      if @rails_version.update(rails_version_params)
        format.html { redirect_to rails_version_url(@rails_version), notice: "Rails version was successfully updated." }
        format.json { render :show, status: :ok, location: @rails_version }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rails_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rails_versions/1 or /rails_versions/1.json
  def destroy
    @rails_version.destroy

    respond_to do |format|
      format.html { redirect_to rails_versions_url, notice: "Rails version was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rails_version
      @rails_version = RailsVersion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rails_version_params
      params.require(:rails_version).permit(:name, :slug, :is_default, :is_active)
    end
end

app/helpers/admin/rails_versions_helper.rb
module Admin::RailsVersionsHelper
end

app/helpers/rails_versions_helper.rb
module RailsVersionsHelper
end

app/views/admin/rails_versions/_form.html.haml
= form_with(model: rails_version, url: (rails_version.persisted? ? Rails.application.routes.url_helpers.admin_rails_version_path(rails_version) : Rails.application.routes.url_helpers.admin_rails_versions_path), class: "contents", data: { turbo_frame: "_top"}) do |form|
  .flex.items-start.justify-between.p-4.border-b.rounded-t.dark:border-gray-600
    %h3.text-xl.font-semibold.text-gray-900.dark:text-white= rails_version.persisted? ? "Update Version" : "Create New Version"
    %button.text-gray-400.bg-transparent.hover:bg-gray-200.hover:text-gray-900.rounded-lg.text-sm.ml-auto.inline-flex.items-center.dark:hover:bg-gray-600.dark:hover:text-white{class: "p-1.5", "data-modal-hide" => rails_version.persisted? ? "version_#{rails_version.id}" : "version_new", type: "button"}
      %svg.w-5.h-5{"aria-hidden" => "true", fill: "currentColor", viewbox: "0 0 20 20", xmlns: "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", d: "M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z", "fill-rule" => "evenodd"}
      %span.sr-only Close modal
  .grid.grid-cols-12.gap-4.px-4.py-6
    .col-span-6
      = form.label :name, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"
      = form.text_field :name, required: true, class: "go-text-field"
    .col-span-12.flex.items-center.gap-4
      = form.check_box :is_active, {class: "w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800", :type => "button"}
      = form.label :is_active, "Active?", class: "block text-sm font-medium text-gray-900 dark:text-white"

  .p-4.flex.justify-end.items-center.gap-4.border-t.dark:border-gray-600
    = form.submit "Submit", class: "block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm py-2 px-5 cursor-pointer text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
    %button.text-gray-500.bg-white.hover:bg-gray-100.focus:ring-4.focus:outline-none.focus:ring-blue-300.rounded-lg.border.border-gray-200.text-sm.font-medium.px-5.hover:text-gray-900.focus:z-10.dark:bg-gray-700.dark:text-gray-300.dark:border-gray-500.dark:hover:text-white.dark:hover:bg-gray-600.dark:focus:ring-gray-600{class: "py-2.5", "data-modal-hide" => rails_version.persisted? ? "version_#{rails_version.id}" : "version_new", type: "button"} Decline

app/views/admin/rails_versions/edit.html.haml
%h1 Editing rails_version

= render 'form'

= link_to 'Show', @rails_version
\|
= link_to 'Back', rails_versions_path

app/views/admin/rails_versions/index.html.haml
.flex.items-center.justify-between.mb-2
	%h3.mb-4.text-2xl.font-extrabold.leading-none.tracking-tight.text-gray-900.md:text-2xl.lg:text-2xl.dark:text-white Rails Versions
	%button.block.text-white.bg-blue-700.hover:bg-blue-800.focus:ring-4.focus:outline-none.focus:ring-blue-300.font-medium.rounded-lg.text-sm.px-5.text-center.dark:bg-blue-600.dark:hover:bg-blue-700.dark:focus:ring-blue-800{class: "py-2.5", "data-modal-target" => "version_new", "data-modal-toggle" => "version_new", type: "button"}
		New Version
#version_new.fixed.top-0.left-0.right-0.z-50.hidden.w-full.p-4.overflow-x-hidden.overflow-y-auto.md:inset-0.h-modal.md:h-full{"aria-hidden" => "true", tabindex: "-1"}
	.relative.w-full.h-full.max-w-2xl.md:h-auto
		.relative.bg-white.rounded-lg.shadow.dark:bg-gray-700
			= render "admin/rails_versions/form", rails_version: @rails_version


.relative.overflow-x-auto.shadow-md.sm:rounded-lg
	= turbo_frame_tag "rails_versions" do
		%table.w-full.text-sm.text-left.text-gray-500.dark:text-gray-400
			%thead.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
				%tr
					%th.px-6.py-3{scope: "col"}
						Version name
					%th.px-6.py-3{scope: "col"}
						Articles
					%th.px-6.py-3{scope: "col"}
						Categories
					%th.px-6.py-3{scope: "col"}
						Slug
					%th.px-6.py-3{scope: "col"}
						Active?
					%th.px-6.py-3{scope: "col"}
						
			%tbody
				- @rails_versions.each do |rv|
					%tr.bg-white.border-b.dark:bg-gray-800.dark:border-gray-700.hover:bg-gray-50.dark:hover:bg-gray-600
						%th.px-6.py-4.font-medium.text-gray-900.whitespace-nowrap.dark:text-white{scope: "row"}
							= rv.try(:name)
						%th.px-6.py-4.font-medium.text-gray-900.whitespace-nowrap.dark:text-white{scope: "row"}
							= rv.articles.count
						%th.px-6.py-4.font-medium.text-gray-900.whitespace-nowrap.dark:text-white{scope: "row"}
							= rv.categories.count
						%td.px-6.py-4
							= rv.try(:slug)
						%td.px-6.py-4
							= rv.try(:is_active) ? "Yes" : "No"
						%td.px-6.py-4
							.flex.items-center.gap-4
								.font-medium.text-blue-600.dark:text-blue-500.cursor-pointer{"data-modal-target" => "version_#{rv.try(:id)}", "data-modal-toggle" => "version_#{rv.try(:id)}", type: "button"} Edit
								.font-medium.text-red-600.dark:text-red-500.cursor-pointer{"data-modal-target" => "delete_version_#{rv.try(:id)}", "data-modal-toggle" => "delete_version_#{rv.try(:id)}", type: "button"} Destroy
							.fixed.top-0.left-0.right-0.z-50.hidden.w-full.p-4.overflow-x-hidden.overflow-y-auto.md:inset-0.h-modal.md:h-full{id: "version_#{rv.try(:id)}", "aria-hidden" => "true", tabindex: "-1"}
								.relative.w-full.h-full.max-w-2xl.md:h-auto
									.relative.bg-white.rounded-lg.shadow.dark:bg-gray-700
										= render "admin/rails_versions/form", rails_version: rv
							.fixed.top-0.left-0.right-0.z-50.hidden.p-4.overflow-x-hidden.overflow-y-auto.md:inset-0.h-modal.md:h-full{id: "delete_version_#{rv.try(:id)}", "aria-hidden" => "true", tabindex: "-1"}
								.relative.w-full.h-full.max-w-md.md:h-auto
									.relative.bg-white.rounded-lg.shadow.dark:bg-gray-700
										= render "admin/shared/destroy_modal", model: rv, url: Rails.application.routes.url_helpers.admin_rails_version_path(rv), id: "delete_version_#{rv.try(:id)}", confirm_text: "Are you sure you want to delete this rails version?"
		
		
		.flex.justify-center
			= will_paginate @rails_versions, :class => "will_pag py-2"

app/views/admin/rails_versions/new.html.haml
%h1 New rails_version

= render 'form'

= link_to 'Back', rails_versions_path

app/views/admin/rails_versions/show.html.haml
%h1 Admin::RailsVersions#show
%p Find me in app/views/admin/rails_versions/show.html.haml