config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles, only: [:index, :show, :create, :update, :destroy]
    resources :categories, only: [:index, :show, :create, :update, :destroy] do
      member do
        patch :update_position
      end
    end
    resources :rails_versions, only: [:index, :show, :create, :update, :destroy]
  end

  get 'admin' => 'admin/articles#index'
  
  resources :articles, only: [:index, :show] do 
    collection do
      get :get_started
      get :what_next
    end
  end
  resources :categories
  resources :rails_versions
  devise_for :users
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/layouts/_navbar.html.haml
%nav.bg-white.px-2.sm:px-4.dark:bg-gray-900.fixed.w-full.z-20.top-0.left-0.border-b.border-gray-200.dark:border-gray-600{:class => "py-2.5"}
  .container.flex.flex-wrap.items-center.mx-auto
    %a.flex.items-center.grow{:href => "https://railsmojo.org/"}
      = image_tag 'railsmojo-logo.png', class: "h-6 mr-3 sm:h-9 light-logo"
      = image_tag 'railsmojo-logo-dark.png', class: "h-6 mr-3 sm:h-9 dark-logo"
      -# %img.h-6.mr-3.sm:h-9{:alt => "Flowbite Logo", :src => "https://flowbite.com/docs/images/logo.svg"}/
      -# %span.self-center.text-xl.font-semibold.whitespace-nowrap.dark:text-white Flowbite
    .flex.md:order-2
      %a#theme-toggle.text-gray-500.dark:text-gray-400.hover:bg-gray-100.dark:hover:bg-gray-700.focus:outline-none.focus:ring-4.focus:ring-gray-200.dark:focus:ring-gray-700.rounded-lg.text-sm{:class => "p-2.5", :type => "button"}
        %svg#theme-toggle-dark-icon.hidden.w-5.h-5{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"}
        %svg#theme-toggle-light-icon.hidden.w-5.h-5{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
          %path{"clip-rule" => "evenodd", :d => "M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z", "fill-rule" => "evenodd"}
      %a.text-gray-500.dark:text-gray-400.hover:bg-gray-100.dark:hover:bg-gray-700.focus:outline-none.focus:ring-4.focus:ring-gray-200.dark:focus:ring-gray-700.rounded-lg.text-sm{:class => "p-2.5", :href => "#"}
        %svg.w-5.h-5{:fill => "currentColor", :viewbox => "0 0 640 512", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M524.531,69.836a1.5,1.5,0,0,0-.764-.7A485.065,485.065,0,0,0,404.081,32.03a1.816,1.816,0,0,0-1.923.91,337.461,337.461,0,0,0-14.9,30.6,447.848,447.848,0,0,0-134.426,0,309.541,309.541,0,0,0-15.135-30.6,1.89,1.89,0,0,0-1.924-.91A483.689,483.689,0,0,0,116.085,69.137a1.712,1.712,0,0,0-.788.676C39.068,183.651,18.186,294.69,28.43,404.354a2.016,2.016,0,0,0,.765,1.375A487.666,487.666,0,0,0,176.02,479.918a1.9,1.9,0,0,0,2.063-.676A348.2,348.2,0,0,0,208.12,430.4a1.86,1.86,0,0,0-1.019-2.588,321.173,321.173,0,0,1-45.868-21.853,1.885,1.885,0,0,1-.185-3.126c3.082-2.309,6.166-4.711,9.109-7.137a1.819,1.819,0,0,1,1.9-.256c96.229,43.917,200.41,43.917,295.5,0a1.812,1.812,0,0,1,1.924.233c2.944,2.426,6.027,4.851,9.132,7.16a1.884,1.884,0,0,1-.162,3.126,301.407,301.407,0,0,1-45.89,21.83,1.875,1.875,0,0,0-1,2.611,391.055,391.055,0,0,0,30.014,48.815,1.864,1.864,0,0,0,2.063.7A486.048,486.048,0,0,0,610.7,405.729a1.882,1.882,0,0,0,.765-1.352C623.729,277.594,590.933,167.465,524.531,69.836ZM222.491,337.58c-28.972,0-52.844-26.587-52.844-59.239S193.056,219.1,222.491,219.1c29.665,0,53.306,26.82,52.843,59.239C275.334,310.993,251.924,337.58,222.491,337.58Zm195.38,0c-28.971,0-52.843-26.587-52.843-59.239S388.437,219.1,417.871,219.1c29.667,0,53.307,26.82,52.844,59.239C470.715,310.993,447.538,337.58,417.871,337.58Z"}
      %a.text-gray-500.dark:text-gray-400.hover:bg-gray-100.dark:hover:bg-gray-700.focus:outline-none.focus:ring-4.focus:ring-gray-200.dark:focus:ring-gray-700.rounded-lg.text-sm{:class => "p-2.5", :href => "https://github.com/orgs/railsmojo/repositories", target: "_blank"}
        %svg.w-5.h-5{:fill => "currentColor", :viewbox => "0 0 496 512", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"}
    #navbar-sticky.items-center.justify-between.hidden.w-full.md:flex.md:w-auto.md:order-1
      %ul.flex.flex-col.p-4.mt-4.border.border-gray-100.rounded-lg.bg-gray-50.md:flex-row.md:space-x-8.md:mt-0.md:text-sm.md:font-medium.md:border-0.md:bg-white.dark:bg-gray-800.md:dark:bg-gray-900.dark:border-gray-700
        %li
          %a.flex.items-center.justify-between.py-2.pl-3.pr-4.text-white.bg-primary-700.rounded.md:bg-transparent.md:text-red-500.md:p-0.dark:text-white{"aria-current" => "page", :href => "#", "data-popover-placement" => "bottom", "data-popover-target" => "popover-bottom"} 
            Learn
            %svg.w-5.h-5.ml-1{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
              %path{"clip-rule" => "evenodd", :d => "M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z", "fill-rule" => "evenodd"}          
        %li
          %a.block.py-2.pl-3.pr-4.text-gray-700.rounded.hover:bg-gray-100.md:hover:bg-transparent.md:hover:text-primary-700.md:p-0.md:dark:hover:text-white.dark:text-gray-400.dark:hover:bg-gray-700.dark:hover:text-white.md:dark:hover:bg-transparent.dark:border-gray-700{:href => "#"} Community

  -# #mega-menu-full-dropdown.hidden.mt-1.border-gray-200.shadow-sm.bg-gray-50.md:bg-white.border-y.dark:bg-gray-800.dark:border-gray-600
  #popover-bottom.absolute.z-10.invisible.inline-block.text-sm.font-light.text-gray-500.transition-opacity.duration-300.bg-white.border.border-gray-200.rounded-lg.shadow-sm.opacity-0.dark:text-gray-400.dark:border-gray-600.dark:bg-gray-800{"data-popover" => "", :role => "tooltip", class: "w-1/2"}  
    %ul.grid.max-w-screen-xl.px-4.py-5.mx-auto.text-gray-900.dark:text-white.sm:grid-cols-2.md:px-6
      - _categories = Category.active
      - _categories.each do |category|
        %li.col-span-1
          = link_to articles_path(category_id: category.id) do
            .block.p-3.rounded-lg.hover:bg-gray-100.dark:hover:bg-gray-700
              .font-semibold= category.try(:name)
              %span.text-sm.font-light.text-gray-500.dark:text-gray-400= category.try(:description)

app/views/layouts/_side_nav.html.haml
%aside#logo-sidebar.fixed.top-0.left-0.w-56.h-screen.bg-white.border-r.border-gray-200.dark:bg-gray-800.dark:border-gray-700
	.px-3.pb-4.bg-white.dark:bg-gray-800
		%a.flex.items-center.grow.py-8{:href => "https://railsmojo.org/"}
			= image_tag 'railsmojo-logo.png', class: "h-6 mr-3 sm:h-9", id: "light-logo"
			= image_tag 'railsmojo-logo-dark.png', class: "h-6 mr-3 sm:h-9", id: "dark-logo"

			
		%ul.space-y-2
			%li
				= link_to root_path, class: "h-min" do
					.flex.items-center.p-2.text-base.font-normal.text-gray-900.rounded-lg.dark:text-white.hover:bg-gray-100.dark:hover:bg-gray-700
						%svg.w-6.h-6.text-gray-500.transition.duration-75.dark:text-gray-400.group-hover:text-gray-900.dark:group-hover:text-white{"aria-hidden" => "true", fill: "currentColor", viewbox: "0 0 20 20", xmlns: "http://www.w3.org/2000/svg"}
							%path{d: "M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"}
							%path{d: "M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"}
						%span.ml-3 Dashboard

			%li
				= link_to Rails.application.routes.url_helpers.admin_articles_path, class: 'h-min' do
					.flex.items-center.p-2.text-base.font-normal.text-gray-900.rounded-lg.dark:text-white.hover:bg-gray-100.dark:hover:bg-gray-700
						%svg.flex-shrink-0.w-6.h-6.text-gray-500.transition.duration-75.dark:text-gray-400{"aria-hidden" => "true", fill: "currentColor", :stroke => "currentColor", viewbox: "0 0 20 20", xmlns: "http://www.w3.org/2000/svg"}
							%path{d: "M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"}
						%span.ml-3 Articles

			%li
				= link_to admin_categories_path, class: "h-min" do
					.flex.items-center.p-2.text-base.font-normal.text-gray-900.rounded-lg.dark:text-white.hover:bg-gray-100.dark:hover:bg-gray-700
						%svg.w-6.h-6.text-gray-500.transition.duration-75.dark:text-gray-400.group-hover:text-gray-900.dark:group-hover:text-white{"aria-hidden" => "true", fill: "currentColor", viewbox: "0 0 20 20", xmlns: "http://www.w3.org/2000/svg"}
							%path{d: "M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"}
							%path{d: "M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"}
						%span.ml-3 Categories

			%li
				= link_to admin_rails_versions_path, class: "h-min" do
					.flex.items-center.p-2.text-base.font-normal.text-gray-900.rounded-lg.dark:text-white.hover:bg-gray-100.dark:hover:bg-gray-700
						%svg.w-6.h-6.text-gray-500.transition.duration-75.dark:text-gray-400.group-hover:text-gray-900.dark:group-hover:text-white{"aria-hidden" => "true", fill: "currentColor", viewbox: "0 0 20 20", xmlns: "http://www.w3.org/2000/svg"}
							%path{d: "M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"}
							%path{d: "M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"}
						%span.ml-3 Rails Versions

			%li
				= link_to Rails.application.routes.url_helpers.destroy_user_session_path, method: :delete, data: { turbo_method: :delete } , class: 'h-min' do
					.flex.items-center.p-2.text-base.font-normal.text-gray-900.rounded-lg.dark:text-white.hover:bg-gray-100.dark:hover:bg-gray-700
						%svg.w-6.h-6.text-gray-500.transition.duration-75.dark:text-gray-400.group-hover:text-gray-900.dark:group-hover:text-white{:fill => "none", :stroke => "currentColor",  :height => "18", :viewbox => "0 0 24 24", :width => "18", :xmlns => "http://www.w3.org/2000/svg"}
							%path{:d => "M16.6667 17.8333L22.5 12M22.5 12L16.6667 6.16667M22.5 12H8.5M8.5 1.5H7.1C5.13982 1.5 4.15973 1.5 3.41103 1.88148C2.75247 2.21703 2.21703 2.75247 1.88148 3.41103C1.5 4.15972 1.5 5.13982 1.5 7.1V16.9C1.5 18.8602 1.5 19.8403 1.88148 20.589C2.21703 21.2475 2.75247 21.783 3.41103 22.1185C4.15972 22.5 5.13982 22.5 7.1 22.5H8.5",  "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
						%span.ml-3 Logout

app/views/layouts/admin.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title railsmojo
		%meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
		= csrf_meta_tags
		= csp_meta_tag
		= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
		= stylesheet_link_tag "application", "data-turbo-track": "reload"
		= javascript_importmap_tags
	%body.dark:bg-gray-900
		= render 'layouts/side_nav'
		.sm:ml-56.pt-20.p-4
			= yield
			

		:javascript
			var lightLogo = document.getElementById('light-logo');
			var darkLogo = document.getElementById('dark-logo');

			// On page load or when changing themes, best to add inline in `head` to avoid FOUC
			if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
					document.documentElement.classList.add('dark');
					lightLogo.classList.add('hidden')
		
			} else {
					document.documentElement.classList.remove('dark')
					darkLogo.classList.add('hidden')
			}

			// Toggle dark theme
			var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');
			var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');

			// Change the icons inside the button based on previous settings
			if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
					themeToggleLightIcon.classList.remove('hidden');
			} else {
					themeToggleDarkIcon.classList.remove('hidden');
			}

			var themeToggleBtn = document.getElementById('theme-toggle');

			themeToggleBtn.addEventListener('click', function() {

					// toggle icons inside button
					themeToggleDarkIcon.classList.toggle('hidden');
					themeToggleLightIcon.classList.toggle('hidden');

					// if set via local storage previously
					if (localStorage.getItem('color-theme')) {
							if (localStorage.getItem('color-theme') === 'light') {
									document.documentElement.classList.add('dark');
									localStorage.setItem('color-theme', 'dark');
									darkLogo.classList.remove('hidden')
									lightLogo.classList.add('hidden')
							} else {
									document.documentElement.classList.remove('dark');
									localStorage.setItem('color-theme', 'light');
									darkLogo.classList.add('hidden')
									lightLogo.classList.remove('hidden')
							}

					// if NOT set via local storage previously
					} else {
							if (document.documentElement.classList.contains('dark')) {
									document.documentElement.classList.remove('dark');
									localStorage.setItem('color-theme', 'light');
									darkLogo.classList.add('hidden')
									lightLogo.classList.remove('hidden')
									
							} else {
									document.documentElement.classList.add('dark');
									localStorage.setItem('color-theme', 'dark');
									darkLogo.classList.remove('hidden')
									lightLogo.classList.add('hidden')
							}
					}
					
			});

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title railsmojo
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body.dark:bg-gray-900
    = render 'layouts/navbar'
    %main
      = yield


  %footer.p-4.bg-gray-50.md:p-8.lg:p-10.dark:bg-gray-800
    .mx-auto.max-w-screen-xl.text-center.flex.flex-col.items-center
      %a.flex.items-center.grow{:href => "https://railsmojo.org/"}
        = image_tag 'railsmojo-icon.png', class: "mr-3 sm:h-9 lg:h-16 light-logo"
        = image_tag 'railsmojo-icon.png', class: "mr-3 sm:h-9 lg:h-16 dark-logo"
      %p.my-6.text-gray-500.dark:text-gray-400 A community of Ruby on Rails Enthusiasts. TODO -> add another sentence here.
      %div.flex.justify-center.items-center.text-base.text-gray-900.dark:text-white
        %ul.flex.flex-wrap.justify-center.items-center.mb-6.text-gray-900.dark:text-white
          %li
            %a.mr-4.hover:underline.md:mr-6{:href => "#"} About
          %li
            %a.mr-4.hover:underline.md:mr-6{:href => "#"} Blog
          %li
            %a.mr-4.hover:underline.md:mr-6{:href => "#"} Events
          %li
            %a.mr-4.hover:underline.md:mr-6{:href => "#"} Community
          %li
            %a.mr-4.hover:underline.md:mr-6{:href => "#"} FAQs
          %li
            %a.mr-4.hover:underline.md:mr-6{:href => "#"} Contact
      %span.text-sm.text-gray-500.sm:text-center.dark:text-gray-400
        © 2023
        = succeed "." do
          %a.hover:underline{:href => "#"} railsmojo
        All Rights Reserved.


    -# %footer.container.mx-auto.mt-28.px-5.flex

    -#     .flex.flex-col
    -#       %s.text-base.text-gray-500 Setup backend system
    -#       %h1.text-2xl Designing UI...
    -#       %h1.text-base.text-gray-500 Configure CMS
    -#       %h1.text-base.text-gray-500 Read data from remote Github repo
    -#       %h1.text-base.text-gray-500 Setup basic scripts
    -#       %h1.text-base.text-gray-500 Define content creation guidelines
    -#       %h1.text-base.text-gray-500 Setup & connect Discord server
    -#       %h1.text-base.text-gray-500 Final Launch

    :javascript
      var lightLogo = document.querySelectorAll('.light-logo');
      var darkLogo = document.querySelectorAll('.dark-logo');
      console.log(darkLogo);
      // On page load or when changing themes, best to add inline in `head` to avoid FOUC
      if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
          document.documentElement.classList.add('dark');
          for (const el of lightLogo) {
            el.classList.add('hidden');
          }
    
      } else {
          document.documentElement.classList.remove('dark')
          for (const el of darkLogo) {
            el.classList.add('hidden');
          }
      }
      // Toggle dark theme
      var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');
      var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');

      // Change the icons inside the button based on previous settings
      if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
          themeToggleLightIcon.classList.remove('hidden');
      } else {
          themeToggleDarkIcon.classList.remove('hidden');
      }

      var themeToggleBtn = document.getElementById('theme-toggle');

      themeToggleBtn.addEventListener('click', function() {

          // toggle icons inside button
          themeToggleDarkIcon.classList.toggle('hidden');
          themeToggleLightIcon.classList.toggle('hidden');

          // if set via local storage previously
          if (localStorage.getItem('color-theme')) {
              if (localStorage.getItem('color-theme') === 'light') {
                  document.documentElement.classList.add('dark');
                  localStorage.setItem('color-theme', 'dark');
                  // darkLogo.classList.remove('hidden')
                  for (const el of darkLogo) {
                    el.classList.remove('hidden');
                  }                  
                  // lightLogo.classList.add('hidden')
                  for (const el of lightLogo) {
                    el.classList.add('hidden');
                  }
              } else {
                  document.documentElement.classList.remove('dark');
                  localStorage.setItem('color-theme', 'light');
                  // darkLogo.classList.add('hidden')
                  for (const el of darkLogo) {
                    el.classList.add('hidden');
                  }
                  // lightLogo.classList.remove('hidden')
                  for (const el of lightLogo) {
                    el.classList.remove('hidden');
                  }                  
              }

          // if NOT set via local storage previously
          } else {
              if (document.documentElement.classList.contains('dark')) {
                  document.documentElement.classList.remove('dark');
                  localStorage.setItem('color-theme', 'light');
                  // darkLogo.classList.add('hidden')
                  for (const el of darkLogo) {
                    el.classList.add('hidden');
                  }                  
                  // lightLogo.classList.remove('hidden')
                  for (const el of lightLogo) {
                    el.classList.remove('hidden');
                  }                  
                  
              } else {
                  document.documentElement.classList.add('dark');
                  localStorage.setItem('color-theme', 'dark');
                  // darkLogo.classList.remove('hidden')
                  for (const el of darkLogo) {
                    el.classList.remove('hidden');
                  }                   
                  // lightLogo.classList.add('hidden')
                  for (const el of lightLogo) {
                    el.classList.add('hidden');
                  }                  

              }
          }
          
      });